[package]
name = "rust-descriptive-statistics"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = "0.3.7"
csv = "1.3.1"
reqwest = { version = "*", features = ["blocking"] }
serde = { version = "*", features = ["derive"] }
